# Generated by Django 3.1.1 on 2020-09-16 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='jobPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=20)),
                ('experience_required', models.CharField(max_length=15)),
                ('skillset_required', models.TextField()),
                ('date_posted', models.DateField()),
                ('job_place', models.CharField(max_length=40)),
                ('job_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='employeeProfile',
            fields=[
                ('referral_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=30)),
                ('posts', models.ManyToManyField(to='referral.jobPost')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
