# Generated by Django 3.1.1 on 2020-09-22 09:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapply',
            name='date_applied',
            field=models.DateField(default=datetime.datetime(2020, 9, 22, 9, 21, 24, 728373, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
