# Generated by Django 3.1.1 on 2020-09-17 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0002_auto_20200917_0641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='employee',
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='posts',
            field=models.ManyToManyField(to='referral.jobPost'),
        ),
    ]
