# Generated by Django 3.1.1 on 2020-09-24 07:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0002_jobapply_date_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapply',
            name='time_delta',
            field=models.DateField(default=datetime.date(2020, 9, 24)),
            preserve_default=False,
        ),
    ]
