# Generated by Django 3.1.1 on 2020-09-17 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0003_auto_20200917_0645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='posts',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='referral.employeeprofile'),
            preserve_default=False,
        ),
    ]
